[http_responses]

[[http_responses.bad]]
code = 404
desc = "Not Found"

[[http_responses.bad]]
code = 503
desc = "Internal Server Error"

[[http_responses.good]]
code = 200
desc = "OK"

[[http_responses.good]]
code = 204
desc = "No Content"

[[persons]]
interests = ["programming", "drawing"]
name = "Matthew Carter"
points = []

[[persons.dynamic]]
a = 0
x = 1

[[persons.dynamic]]
a = 1
y = 2

[[persons]]
dynamic = []
interests = ["sleeping"]
name = "Jon Smith"

[[persons.points]]
name = "First point"
x = 1
y = 2.3

[[persons.points]]
name = "second point"
x = 3
y = 4.9

[[persons.points]]
name = "third point"
x = 5
y = 6.0

[[persons.points]]
name = "fourth point"
x = 7
y = 8.32

[[persons.points]]
name = "fifth point"
x = 9
y = 10.1

[[points]]
name = "First point"
x = 1
y = 2.3

[[points]]
name = "second point"
x = 3
y = 4.9

[[points]]
name = "third point"
x = 5
y = 6.0

[[points]]
name = "fourth point"
x = 7
y = 8.32

[[points]]
name = "fifth point"
x = 9
y = 10.1
